# pin clang<15 because cppyy (and cling) need an old enough libcxx, see
# https://github.com/conda-forge/cppyy-feedstock/blob/main/recipe/meta.yaml
c_compiler_version:        # [osx]
  - 14                     # [osx]
cxx_compiler_version:      # [osx]
  - 14                     # [osx]
MACOSX_DEPLOYMENT_TARGET:  # [osx and x86_64]
  - 11.0                   # [osx and x86_64]
MACOSX_SDK_VERSION:        # [osx and x86_64]
  - 11.0                   # [osx and x86_64]
