travis:
  secure:
    BINSTAR_TOKEN: snNKYSvmXL3PYDwh0YBCl5Qd2b3VIkRrRqGR4+CqdLAW7nXfcGcOlURu55aUuinjj+okdCKmZh8oFnzCMgi4wI2icniatQihtsHvYT3AV6wjkIxdY0ftX+QCHq3EcOLp4UUnYCuNWqvPW2ueUZNM8IToHWGvgTQGFWqLuIeubbn++Vt2zoucDxgYCIr9QVBkE0C+zJvkTnxxjTsNnvZR0PTSMreEupWW47HCgZmDCZXuzHPdJoSkzSaRGiQO9xAlSL0UhpMu1n+WeWCErM86QKL+ARl8n0rBPPtg9DGMIAvlOp/zm8l2AV8cMm1n/38igGCcRhkJeqd3MFQ2Y0HE0QhN5OG1m2j+ITZmanQwgVd1VNh8oNgIpse9v9dhvLMsOX5BakyrkfHpH0QNNaOoUWvT1E5gf+cpnGnVt7AWE1xQ+TvhrKxhTlqtupgt26XExxiIVcfbOYN88wpq/Ndzp96unKjRYz8Fl6voKEA2efhAnG1ThkTxrTh9lCKph0MT1IZTSbTPnme+RAvEC7uDLo6uylL/UE0ARZXtzVTF6OTTN3AGFHMPHrPyJqcbSevE3YlhShfKiOibjj22VlrT/zMGxXWDfs8/uRy3rZkbfLOT+9a87IrGPCQtR+gJiMlA1BYz86UfNtmVDbRvpvrEU1bvvmRxgQmcUpivsVo67i8=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
